=head1 NAME

README - Readme file for Parrot's 'parrot-docs1' documentation repository.

=head1 DESCRIPTION

The purpose of this README is to record the fact that this repository contains 
the documentation for version 1.0.0 through version 1.9.0 of Parrot.  In 
short, this repository is, in-the-main, about maintaining a set of all of 
Parrot's documentation on github.

=head1 COPYRIGHT

Copyright (C) 2011, Parrot Foundation.

=cut
